# Generated by Django 2.0.2 on 2018-02-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RingoProductingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(max_length=10, verbose_name='都道府県名')),
                ('ratio', models.PositiveSmallIntegerField(default=0, verbose_name='割合')),
            ],
        ),
    ]
